[package]
name = "snek"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "^0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sdl2 = {version = "^0.35", features = ["ttf"]}


[target.'cfg(not(target_os = "emscripten"))'.dependencies]
directories = "4.0.1"
